### PR TITLE
Attempt to sort non-valid version numbers

### PR DESCRIPTION
**Pull request by elsmorian**
I have no Ruby skills, but from a super quick Google this might work - just to attempt to sort based on defaults for other tag version names

### CODE REVIEW

**Comment by elsmorian** [comment]
Had a little bit of free time and so built this just to check that I hadn't screwed up the syntax- the sort addition solves our needs, and sorts the lists nicely :)

**Comment by parabuzzle** [comment]
@elsmorian thank you for the contribution.

**Comment by elsmorian** [comment]
@parabuzzle No problem :) Any chance of a new image on the docker registry?

**Comment by parabuzzle** [comment]
Continuous Integration and Deployment does it automatically when merged to master.. It appears that your changes are in version 2.1.8 on dockerhub (https://circleci.com/gh/parabuzzle/craneoperator/53)

**Pull request merged**
