### PR TITLE
Run behind a web server 

### PR DESCRIPTION
**Pull request by PauloFerreira25**
Hello gentlemen,

Please accept my pull request.

I made changes to allow the application to run behind a web server (eg nginx).

Thanks for listening

### CODE REVIEW

**Comment by danielriddell21** [comment]
@PauloFerreira25 Why was this closed?

**Comment by PauloFerreira25** [comment]
@bobland1 
I don't remember why I closed this pull request.
But I believe it is because I found a way to do it in nginx without having to change the code. Doing some configuration.
Sorry I can't help you.

**Comment by danielriddell21** [comment]
@PauloFerreira25 Can you tell me how you configured it on nginx?

**Comment by PauloFerreira25** [comment]
@bobland1 
Unfortunately, I can't see what I did anymore.
I did this job for a company as a freelancer and I no longer have access to the settings.
I'm sorry.

**Pull request closed without merging**
